apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app
  description: Hello World Application
spec:
  type: service
  lifecycle: production
  owner: rainisingh
  containers:
    - image: rainisingh/hello-world-app:1.0.0
  providesApis:
    - kind: Website
      environment: production
      host: localhost
      port: 5000  # Adjust the port according to your application's configuration
