apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-docker
  description: Hello, World! Example Component
  annotations:
    github.com/project-slug: Raini0703/hello-world
spec:
  type: website
  owner: Raini0703
  lifecycle: experimental
