apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-app
  description: hello-world pyhton app
  annotations:
    github.com/project-slug: Raini0703/hello-world
spec:
  type: service
  owner: Raini0703/hello-world
  lifecycle: experimental
