apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-docker
  description: Python Dockerized Application
  annotations:
    github.com/project-slug: Raini0703/hello-world
spec:
  type: service
  owner: raini0703
  lifecycle: experimental
  providesApis:
    - kind: Website
      environment: production
      host: localhost
      port: 3000

  containers:
    - name: main
      image: docker.io/library/python:3.8-slim
      command: ["python", "HelloWorld.py"]
      workDir: /app
      ports:
        - port: 8000
      environment:
        - key: PYTHONUNBUFFERED
          value: "1"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: code
          mountPath: /app
