name: Trigger Jenkins Job

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl "http://localhost:8080/buildByToken/build?job=demo-4th&token=raini1"
